title: Kohomai documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://kohomai.github.io

repository: kohomai/kohomai.github.io # for github-metadata

# External navigation links
nav_external_links:
  - title: API
    url: https://app.swaggerhub.com/apis-docs/Kohomai/api/1.0.0
  - title: App
    url: https://app.kohomai.com
  - title: Website
    url: https://kohomai.com

logo: "/assets/logo.png"
favicon_ico: "/assets/favicon.png"

footer_content: "&copy; 2023 Kohomai GmbH"
